/*
 * elev8er Public API
 * Team-scoped public API for elev8er. Authenticate every request with an API key issued per team (`X-API-Key` header). Keys are created and managed from the elev8er panel (Team › API Keys). This API is intended for **server-to-server** use — never expose your API key in a browser or mobile client.  **Rate limiting:** every response includes `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers. When the limit is exceeded the API returns `429 Too Many Requests`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@elev8er.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.elev8er.publicapi.api;

import ai.elev8er.publicapi.ApiException;
import ai.elev8er.publicapi.model.ChatMessageInput;
import ai.elev8er.publicapi.model.CreateAgentChatRequest;
import ai.elev8er.publicapi.model.Error;
import ai.elev8er.publicapi.model.SuccessEnvelope;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AgentsApi
 */
@Disabled
public class AgentsApiTest {

    private final AgentsApi api = new AgentsApi();

    /**
     * Start a new chat with an agent
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createAgentChatTest() throws ApiException {
        String id = null;
        CreateAgentChatRequest createAgentChatRequest = null;
        SuccessEnvelope response = api.createAgentChat(id, createAgentChatRequest);
        // TODO: test validations
    }

    /**
     * Get an agent by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAgentTest() throws ApiException {
        String id = null;
        SuccessEnvelope response = api.getAgent(id);
        // TODO: test validations
    }

    /**
     * List chats for an agent
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAgentChatsTest() throws ApiException {
        String id = null;
        SuccessEnvelope response = api.listAgentChats(id);
        // TODO: test validations
    }

    /**
     * List agents
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAgentsTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        SuccessEnvelope response = api.listAgents(page, limit);
        // TODO: test validations
    }

    /**
     * Get messages in a chat
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listChatMessagesTest() throws ApiException {
        String id = null;
        String chatId = null;
        Integer page = null;
        Integer limit = null;
        SuccessEnvelope response = api.listChatMessages(id, chatId, page, limit);
        // TODO: test validations
    }

    /**
     * Send a message to the agent and get its reply (non-streaming)
     *
     * Sends a user message to the agent and returns the agent&#39;s full reply in a single JSON response. Streaming is not exposed on the public API. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sendChatMessageTest() throws ApiException {
        String id = null;
        String chatId = null;
        ChatMessageInput chatMessageInput = null;
        SuccessEnvelope response = api.sendChatMessage(id, chatId, chatMessageInput);
        // TODO: test validations
    }

}
