/*
 * elev8er Public API
 * Team-scoped public API for elev8er. Authenticate every request with an API key issued per team (`X-API-Key` header). Keys are created and managed from the elev8er panel (Team › API Keys). This API is intended for **server-to-server** use — never expose your API key in a browser or mobile client.  **Rate limiting:** every response includes `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers. When the limit is exceeded the API returns `429 Too Many Requests`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@elev8er.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.elev8er.publicapi.api;

import ai.elev8er.publicapi.ApiException;
import ai.elev8er.publicapi.model.Error;
import ai.elev8er.publicapi.model.SuccessEnvelope;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BlogsApi
 */
@Disabled
public class BlogsApiTest {

    private final BlogsApi api = new BlogsApi();

    /**
     * Create a blog
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createBlogTest() throws ApiException {
        Map<String, Object> requestBody = null;
        SuccessEnvelope response = api.createBlog(requestBody);
        // TODO: test validations
    }

    /**
     * Delete a blog
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteBlogTest() throws ApiException {
        String id = null;
        api.deleteBlog(id);
        // TODO: test validations
    }

    /**
     * Get a blog by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBlogTest() throws ApiException {
        String id = null;
        SuccessEnvelope response = api.getBlog(id);
        // TODO: test validations
    }

    /**
     * List blogs
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listBlogsTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        String search = null;
        SuccessEnvelope response = api.listBlogs(page, limit, search);
        // TODO: test validations
    }

    /**
     * Update a blog
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateBlogTest() throws ApiException {
        String id = null;
        Map<String, Object> requestBody = null;
        SuccessEnvelope response = api.updateBlog(id, requestBody);
        // TODO: test validations
    }

}
