/*
 * elev8er Public API
 * Team-scoped public API for elev8er. Authenticate every request with an API key issued per team (`X-API-Key` header). Keys are created and managed from the elev8er panel (Team › API Keys). This API is intended for **server-to-server** use — never expose your API key in a browser or mobile client.  **Rate limiting:** every response includes `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers. When the limit is exceeded the API returns `429 Too Many Requests`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@elev8er.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.elev8er.publicapi.api;

import ai.elev8er.publicapi.ApiException;
import ai.elev8er.publicapi.model.Error;
import ai.elev8er.publicapi.model.SuccessEnvelope;
import ai.elev8er.publicapi.model.UpdateSessionStatusRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExpertsApi
 */
@Disabled
public class ExpertsApiTest {

    private final ExpertsApi api = new ExpertsApi();

    /**
     * Create an availability entry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createAvailabilityTest() throws ApiException {
        Object body = null;
        SuccessEnvelope response = api.createAvailability(body);
        // TODO: test validations
    }

    /**
     * Create an expert
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createExpertTest() throws ApiException {
        Map<String, Object> requestBody = null;
        SuccessEnvelope response = api.createExpert(requestBody);
        // TODO: test validations
    }

    /**
     * Create a session
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSessionTest() throws ApiException {
        Object body = null;
        SuccessEnvelope response = api.createSession(body);
        // TODO: test validations
    }

    /**
     * Delete an availability entry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteAvailabilityTest() throws ApiException {
        String id = null;
        api.deleteAvailability(id);
        // TODO: test validations
    }

    /**
     * Delete an expert
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteExpertTest() throws ApiException {
        String id = null;
        api.deleteExpert(id);
        // TODO: test validations
    }

    /**
     * Delete a session
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteSessionTest() throws ApiException {
        String id = null;
        api.deleteSession(id);
        // TODO: test validations
    }

    /**
     * Get an availability entry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAvailabilityTest() throws ApiException {
        String id = null;
        SuccessEnvelope response = api.getAvailability(id);
        // TODO: test validations
    }

    /**
     * Get an expert by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getExpertTest() throws ApiException {
        String id = null;
        SuccessEnvelope response = api.getExpert(id);
        // TODO: test validations
    }

    /**
     * Get an expert&#39;s availability
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getExpertAvailabilityTest() throws ApiException {
        String expertId = null;
        SuccessEnvelope response = api.getExpertAvailability(expertId);
        // TODO: test validations
    }

    /**
     * Get a session
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSessionTest() throws ApiException {
        String id = null;
        SuccessEnvelope response = api.getSession(id);
        // TODO: test validations
    }

    /**
     * List sessions for an expert
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listExpertSessionsTest() throws ApiException {
        String expertId = null;
        SuccessEnvelope response = api.listExpertSessions(expertId);
        // TODO: test validations
    }

    /**
     * List experts
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listExpertsTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        String search = null;
        SuccessEnvelope response = api.listExperts(page, limit, search);
        // TODO: test validations
    }

    /**
     * List sessions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listSessionsTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        SuccessEnvelope response = api.listSessions(page, limit);
        // TODO: test validations
    }

    /**
     * Replace an expert&#39;s availability
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setExpertAvailabilityTest() throws ApiException {
        String expertId = null;
        Object body = null;
        SuccessEnvelope response = api.setExpertAvailability(expertId, body);
        // TODO: test validations
    }

    /**
     * Update an availability entry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateAvailabilityTest() throws ApiException {
        String id = null;
        Object body = null;
        SuccessEnvelope response = api.updateAvailability(id, body);
        // TODO: test validations
    }

    /**
     * Update an expert
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateExpertTest() throws ApiException {
        String id = null;
        Map<String, Object> requestBody = null;
        SuccessEnvelope response = api.updateExpert(id, requestBody);
        // TODO: test validations
    }

    /**
     * Update a session
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSessionTest() throws ApiException {
        String id = null;
        Object body = null;
        SuccessEnvelope response = api.updateSession(id, body);
        // TODO: test validations
    }

    /**
     * Update a session&#39;s status
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSessionStatusTest() throws ApiException {
        String id = null;
        UpdateSessionStatusRequest updateSessionStatusRequest = null;
        SuccessEnvelope response = api.updateSessionStatus(id, updateSessionStatusRequest);
        // TODO: test validations
    }

}
