/*
 * elev8er Public API
 * Team-scoped public API for elev8er. Authenticate every request with an API key issued per team (`X-API-Key` header). Keys are created and managed from the elev8er panel (Team › API Keys). This API is intended for **server-to-server** use — never expose your API key in a browser or mobile client.  **Rate limiting:** every response includes `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers. When the limit is exceeded the API returns `429 Too Many Requests`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@elev8er.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.elev8er.publicapi.api;

import ai.elev8er.publicapi.ApiException;
import ai.elev8er.publicapi.model.CreateProgramTagRequest;
import ai.elev8er.publicapi.model.Error;
import ai.elev8er.publicapi.model.ListPrograms200Response;
import ai.elev8er.publicapi.model.SetProgramTagsRequest;
import ai.elev8er.publicapi.model.SuccessEnvelope;
import ai.elev8er.publicapi.model.UpdateProgramTagRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProgramsApi
 */
@Disabled
public class ProgramsApiTest {

    private final ProgramsApi api = new ProgramsApi();

    /**
     * Create a program
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createProgramTest() throws ApiException {
        Map<String, Object> requestBody = null;
        SuccessEnvelope response = api.createProgram(requestBody);
        // TODO: test validations
    }

    /**
     * Create a program tag
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createProgramTagTest() throws ApiException {
        CreateProgramTagRequest createProgramTagRequest = null;
        SuccessEnvelope response = api.createProgramTag(createProgramTagRequest);
        // TODO: test validations
    }

    /**
     * Create a new version of a program
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createProgramVersionTest() throws ApiException {
        String id = null;
        Object body = null;
        SuccessEnvelope response = api.createProgramVersion(id, body);
        // TODO: test validations
    }

    /**
     * Delete a program
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteProgramTest() throws ApiException {
        String id = null;
        api.deleteProgram(id);
        // TODO: test validations
    }

    /**
     * Delete a program tag
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteProgramTagTest() throws ApiException {
        String tagId = null;
        api.deleteProgramTag(tagId);
        // TODO: test validations
    }

    /**
     * Get a program by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProgramTest() throws ApiException {
        String id = null;
        SuccessEnvelope response = api.getProgram(id);
        // TODO: test validations
    }

    /**
     * Get tags assigned to a program
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProgramTagsTest() throws ApiException {
        String id = null;
        SuccessEnvelope response = api.getProgramTags(id);
        // TODO: test validations
    }

    /**
     * Get a specific program version
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProgramVersionTest() throws ApiException {
        String id = null;
        String versionId = null;
        SuccessEnvelope response = api.getProgramVersion(id, versionId);
        // TODO: test validations
    }

    /**
     * List program tags
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listProgramTagsTest() throws ApiException {
        SuccessEnvelope response = api.listProgramTags();
        // TODO: test validations
    }

    /**
     * List versions of a program
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listProgramVersionsTest() throws ApiException {
        String id = null;
        SuccessEnvelope response = api.listProgramVersions(id);
        // TODO: test validations
    }

    /**
     * List programs
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listProgramsTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        String search = null;
        ListPrograms200Response response = api.listPrograms(page, limit, search);
        // TODO: test validations
    }

    /**
     * Roll a program back to a specific version
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void rollbackProgramVersionTest() throws ApiException {
        String id = null;
        String versionId = null;
        SuccessEnvelope response = api.rollbackProgramVersion(id, versionId);
        // TODO: test validations
    }

    /**
     * Replace the tags assigned to a program
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setProgramTagsTest() throws ApiException {
        String id = null;
        SetProgramTagsRequest setProgramTagsRequest = null;
        SuccessEnvelope response = api.setProgramTags(id, setProgramTagsRequest);
        // TODO: test validations
    }

    /**
     * Update a program
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateProgramTest() throws ApiException {
        String id = null;
        Map<String, Object> requestBody = null;
        SuccessEnvelope response = api.updateProgram(id, requestBody);
        // TODO: test validations
    }

    /**
     * Update a program tag
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateProgramTagTest() throws ApiException {
        String tagId = null;
        UpdateProgramTagRequest updateProgramTagRequest = null;
        SuccessEnvelope response = api.updateProgramTag(tagId, updateProgramTagRequest);
        // TODO: test validations
    }

    /**
     * Update a specific program version
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateProgramVersionTest() throws ApiException {
        String id = null;
        String versionId = null;
        Object body = null;
        SuccessEnvelope response = api.updateProgramVersion(id, versionId, body);
        // TODO: test validations
    }

}
