/*
 * elev8er Public API
 * Team-scoped public API for elev8er. Authenticate every request with an API key issued per team (`X-API-Key` header). Keys are created and managed from the elev8er panel (Team › API Keys). This API is intended for **server-to-server** use — never expose your API key in a browser or mobile client.  **Rate limiting:** every response includes `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers. When the limit is exceeded the API returns `429 Too Many Requests`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@elev8er.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.elev8er.publicapi.api;

import ai.elev8er.publicapi.ApiException;
import ai.elev8er.publicapi.model.Error;
import ai.elev8er.publicapi.model.SuccessEnvelope;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TestsApi
 */
@Disabled
public class TestsApiTest {

    private final TestsApi api = new TestsApi();

    /**
     * Create a test
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTestTest() throws ApiException {
        Map<String, Object> requestBody = null;
        SuccessEnvelope response = api.createTest(requestBody);
        // TODO: test validations
    }

    /**
     * Create a new version of a test
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTestVersionTest() throws ApiException {
        String id = null;
        Object body = null;
        SuccessEnvelope response = api.createTestVersion(id, body);
        // TODO: test validations
    }

    /**
     * Delete a test
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteTestTest() throws ApiException {
        String id = null;
        api.deleteTest(id);
        // TODO: test validations
    }

    /**
     * Get a test by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTestTest() throws ApiException {
        String id = null;
        SuccessEnvelope response = api.getTest(id);
        // TODO: test validations
    }

    /**
     * Get a specific test version
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTestVersionTest() throws ApiException {
        String id = null;
        String versionId = null;
        SuccessEnvelope response = api.getTestVersion(id, versionId);
        // TODO: test validations
    }

    /**
     * List versions of a test
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTestVersionsTest() throws ApiException {
        String id = null;
        SuccessEnvelope response = api.listTestVersions(id);
        // TODO: test validations
    }

    /**
     * List tests
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTestsTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        String search = null;
        SuccessEnvelope response = api.listTests(page, limit, search);
        // TODO: test validations
    }

    /**
     * Roll a test back to a specific version
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void rollbackTestVersionTest() throws ApiException {
        String id = null;
        String versionId = null;
        SuccessEnvelope response = api.rollbackTestVersion(id, versionId);
        // TODO: test validations
    }

    /**
     * Update a test
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTestTest() throws ApiException {
        String id = null;
        Map<String, Object> requestBody = null;
        SuccessEnvelope response = api.updateTest(id, requestBody);
        // TODO: test validations
    }

    /**
     * Update a specific test version
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTestVersionTest() throws ApiException {
        String id = null;
        String versionId = null;
        Object body = null;
        SuccessEnvelope response = api.updateTestVersion(id, versionId, body);
        // TODO: test validations
    }

}
