/*
 * elev8er Public API
 * Team-scoped public API for elev8er. Authenticate every request with an API key issued per team (`X-API-Key` header). Keys are created and managed from the elev8er panel (Team › API Keys). This API is intended for **server-to-server** use — never expose your API key in a browser or mobile client.  **Rate limiting:** every response includes `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers. When the limit is exceeded the API returns `429 Too Many Requests`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@elev8er.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.elev8er.publicapi.api;

import ai.elev8er.publicapi.ApiException;
import ai.elev8er.publicapi.model.Error;
import ai.elev8er.publicapi.model.SuccessEnvelope;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VisualTestsApi
 */
@Disabled
public class VisualTestsApiTest {

    private final VisualTestsApi api = new VisualTestsApi();

    /**
     * Create a visual test
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createVisualTestTest() throws ApiException {
        Map<String, Object> requestBody = null;
        SuccessEnvelope response = api.createVisualTest(requestBody);
        // TODO: test validations
    }

    /**
     * Create a new version of a visual test
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createVisualTestVersionTest() throws ApiException {
        String id = null;
        Object body = null;
        SuccessEnvelope response = api.createVisualTestVersion(id, body);
        // TODO: test validations
    }

    /**
     * Delete a visual test
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteVisualTestTest() throws ApiException {
        String id = null;
        api.deleteVisualTest(id);
        // TODO: test validations
    }

    /**
     * Get a visual test by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVisualTestTest() throws ApiException {
        String id = null;
        SuccessEnvelope response = api.getVisualTest(id);
        // TODO: test validations
    }

    /**
     * Get a specific visual test version
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVisualTestVersionTest() throws ApiException {
        String id = null;
        String versionId = null;
        SuccessEnvelope response = api.getVisualTestVersion(id, versionId);
        // TODO: test validations
    }

    /**
     * List versions of a visual test
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listVisualTestVersionsTest() throws ApiException {
        String id = null;
        SuccessEnvelope response = api.listVisualTestVersions(id);
        // TODO: test validations
    }

    /**
     * List visual tests
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listVisualTestsTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        String search = null;
        SuccessEnvelope response = api.listVisualTests(page, limit, search);
        // TODO: test validations
    }

    /**
     * Roll a visual test back to a specific version
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void rollbackVisualTestVersionTest() throws ApiException {
        String id = null;
        String versionId = null;
        SuccessEnvelope response = api.rollbackVisualTestVersion(id, versionId);
        // TODO: test validations
    }

    /**
     * Update a visual test
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateVisualTestTest() throws ApiException {
        String id = null;
        Map<String, Object> requestBody = null;
        SuccessEnvelope response = api.updateVisualTest(id, requestBody);
        // TODO: test validations
    }

    /**
     * Update a specific visual test version
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateVisualTestVersionTest() throws ApiException {
        String id = null;
        String versionId = null;
        Object body = null;
        SuccessEnvelope response = api.updateVisualTestVersion(id, versionId, body);
        // TODO: test validations
    }

}
